import {
  Sprout,
  Cpu,
  History,
  BarChart3,
  BookOpen,
  Settings,
  ShieldCheck,
  AlertTriangle,
  CheckCircle,
  HelpCircle,
  Upload,
  ArrowRight,
  ArrowLeft,
  Download,
  RotateCcw,
  Menu,
  Sun,
  Moon,
  Wifi,
  WifiOff,
  Trash2,
  Info,
} from 'lucide-react'

export const icons = {
  agriculture: Sprout,
  ai: Cpu,
  history: History,
  analytics: BarChart3,
  encyclopedia: BookOpen,
  settings: Settings,
  shield: ShieldCheck,
  warning: AlertTriangle,
  success: CheckCircle,
  help: HelpCircle,
  upload: Upload,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  download: Download,
  reset: RotateCcw,
  menu: Menu,
  sun: Sun,
  moon: Moon,
  wifi: Wifi,
  wifiOff: WifiOff,
  trash: Trash2,
  info: Info,
} as const;

export type AppIconType = keyof typeof icons;
